name: List services in GCP
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - nonprod
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  Get-OIDC-Token-and-List:
    strategy:
      fail-fast: false
      matrix:
        environment: [nonprod]

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CREDENTIALS_JSON_NONPROD }}'


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud storage ls'