name: List services in GCP
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - nonprod
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  Get-OIDC-Token-and-List:
    strategy:
      fail-fast: false
      matrix:
        environment: [nonprod, prod]

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Set up Nonprod Secret'
        if: ${{ matrix.environment }} == 'nonprod'
        run: echo "CREDENTIALS_JSON=${{ secrets.CREDENTIALS_JSON_NONPROD }}" >> $GITHUB_ENV

      - name: 'Set up Prod Secret'
        if: ${{ matrix.environment }} == 'prod'
        run: echo "CREDENTIALS_JSON=${{ secrets.CREDENTIALS_JSON_PROD }}" >> $GITHUB_ENV

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.CREDENTIALS_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: gcloud storage ls