name: List services in GCP
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    branches:
      - nonprod
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  Get-OIDC-Token-and-List:
    strategy:
      fail-fast: false
      matrix:
        environment: [nonprod]

    runs-on: ubuntu-latest

    steps:
      - uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'fast-tensor-430421-i4'
          service_account: 'service-account-${{ matrix.environment }}@fast-tensor-430421-i4.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/408970351360/locations/global/workloadIdentityPools/github-pool-${{ matrix.environment }}/providers/github-provider-${{ matrix.environment }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'